### ISSUE TITLE
Quality Audit: Run clang-tidy in up-transport-zenoh-cpp and file bugs for all findings

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-transport-zenoh-cpp#71]

**Comment by debruce** [comment]
I would be happy to look into this.

**Comment by gregmedd** [comment]
@debruce - Feel free to start that work. The goal is not to fix the issues found, but to log them as bugs (divided by file or function, whichever keeps the tasks as manageable sizes). This way we can review, prioritize, and divide up these tasks across contributors.

**Comment by debruce** [comment]
clang-tidy-12 on up-transport-zenoh-cpp found about 95 warnings and 7 errors. The 95 warnings in about 11 groups. These look pretty easily fixable. In order to do this exploration, I needed to copy the clang-tidy.sh from up-cpp to the lint directory of up-transport-zenoh-cpp.

**Comment by debruce** [comment]
An issue has been created for each source file with clang-tidy warnings in up-transport-zenoh-cpp.
That completes this task.
